#!/usr/bin/env bash

wall_dir="$HOME/Pictures/wallpapers"

# Pick a random wallpaper
wallpaper=$(find "$wall_dir" -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" -o -iname "*.webp" \) | shuf -n 1)

# Set wallpaper and update waybar color
swww img "$wallpaper" -t grow --transition-duration 2 --transition-fps 75
colorwaybar "$wallpaper" 
